name: "Tests"

on:
  push:
    paths:
      - ".github/**/*"
      - "src/*"
      - "src/**/*"
      - "*.js"
      - "*.json"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["10.x", "12.x"]
    name: Node ${{ matrix.version }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: npm install
      - name: Build test
        run: npm run build
      - name: Unit test
        run: npm test

      - name: "Slack notification (not success)"
        uses: homoluctus/slatify@master
        if: "! success()"
        with:
          type: ${{ job.status }}
          job_name: ":togowl::nodejs:*${{ matrix.version }}* Tests failure @channel"
          icon_emoji: "tio2"
          url: ${{ secrets.SLACK_WEBHOOK }}

  notify:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: "Slack Notification (success)"
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ":togowl::nodejs: All tests success :+1:"
          icon_emoji: ":renne:"
          url: ${{ secrets.SLACK_WEBHOOK }}
